extern crate self as bevy_filter_enum;

use bevy_ecs::schedule::SystemSet;
use bevy_ecs::system::EntityCommands;

pub use bevy_filter_enum_derive::{EnumFilter, EnumFilterCollection};

/// Label for the `PreUpdate` systems every generated plugin uses to catch
/// in-place enum mutations. Order your own systems after this set when they
/// need to see markers that reflect changes made through `Mut<Enum>`.
///
/// Inserting or removing the enum through commands or `EntityWorldMut` is
/// handled by component hooks and is visible immediately, this set only
/// matters for `DerefMut` style edits.
#[derive(Debug, Hash, PartialEq, Eq, Clone, SystemSet)]
pub struct EnumFilterSystems;

/// Shared behavior generated by [`EnumFilter`] for enum values that can sync
/// marker components onto an entity.
///
/// Every method leaves markers that are already in the right state untouched,
/// so `Add` and `Remove` hooks and observers fire only on real variant
/// transitions and not when the enum is re-inserted with the same variant.
pub trait EnumFilterValue {
    /// Returns the generated marker index for this enum value.
    fn marker_index(&self) -> usize;

    /// Syncs the markers so that only the one at `index` is present.
    ///
    /// This is the fast path for a single active variant: one insert for the
    /// active marker and one bundle remove for the rest. Indexes outside the
    /// variant range are ignored.
    fn sync_marker_at(index: usize, entity: &mut EntityCommands<'_>);

    /// Syncs the markers so that only the one for this enum value is present.
    fn sync_marker(&self, entity: &mut EntityCommands<'_>) {
        Self::sync_marker_at(self.marker_index(), entity);
    }

    /// Brings the generated marker components in line with `active`: the
    /// marker for every index `active` accepts is added if missing, and every
    /// other marker is removed if present.
    ///
    /// Use this when several variants can be active at once, as with
    /// [`EnumFilterCollection`]. It queues one command per marker, so prefer
    /// [`sync_marker`](Self::sync_marker) when only one variant is active.
    fn sync_markers(active: impl Fn(usize) -> bool, entity: &mut EntityCommands<'_>);

    /// Removes all marker components generated for this enum type.
    fn remove_markers(entity: &mut EntityCommands<'_>);
}

/// Re-exports so the derive output can refer to known crate paths.
pub mod __private {
    pub use bevy_app;
    pub use bevy_ecs;
}

#[cfg(test)]
mod tests {
    use bevy_app::{App, PreUpdate};
    use bevy_ecs::lifecycle::{Add, Discard, Insert, Remove};
    use bevy_ecs::prelude::{
        Commands, Component, IntoScheduleConfigs, On, Query, ResMut, Resource, With,
    };
    use strum_macros::Display;

    use crate::{EnumFilter, EnumFilterCollection, EnumFilterSystems};

    /// Counts of every lifecycle event observed for one component type.
    #[derive(Resource, Default, Debug, Clone, PartialEq, Eq)]
    struct Transitions {
        add: usize,
        insert: usize,
        discard: usize,
        remove: usize,
    }

    /// Tallies `Add`, `Insert`, `Discard` and `Remove` for `C` into
    /// [`Transitions`], so tests can assert exactly which transitions a
    /// marker or extracted payload went through.
    fn observe_transitions<C: Component>(app: &mut App) {
        app.init_resource::<Transitions>();
        app.add_observer(|_: On<Add, C>, mut counts: ResMut<Transitions>| counts.add += 1);
        app.add_observer(|_: On<Insert, C>, mut counts: ResMut<Transitions>| {
            counts.insert += 1;
        });
        app.add_observer(|_: On<Discard, C>, mut counts: ResMut<Transitions>| {
            counts.discard += 1;
        });
        app.add_observer(|_: On<Remove, C>, mut counts: ResMut<Transitions>| {
            counts.remove += 1;
        });
    }

    fn transitions(app: &App) -> Transitions {
        app.world().resource::<Transitions>().clone()
    }

    #[derive(Component, EnumFilter, Debug, PartialEq, Eq)]
    enum Mode {
        Idle,
        Run,
    }

    #[test]
    fn markers_are_synced_immediately_on_insert() {
        let mut app = App::new();
        app.add_plugins(ModeEnumFilterPlugin);

        let entity = app.world_mut().spawn(Mode::Idle).id();
        let entity_ref = app.world().entity(entity);

        assert!(entity_ref.contains::<ModeIdle>());
        assert!(!entity_ref.contains::<ModeRun>());
    }

    #[test]
    fn markers_are_removed_immediately_on_component_removal() {
        let mut app = App::new();
        app.add_plugins(ModeEnumFilterPlugin);

        let entity = app.world_mut().spawn(Mode::Idle).id();
        app.world_mut().entity_mut(entity).remove::<Mode>();
        let entity_ref = app.world().entity(entity);

        assert!(!entity_ref.contains::<ModeIdle>());
        assert!(!entity_ref.contains::<ModeRun>());
    }

    #[test]
    fn reinserting_same_variant_leaves_marker_untouched() {
        let mut app = App::new();
        app.add_plugins(ModeEnumFilterPlugin);
        observe_transitions::<ModeIdle>(&mut app);

        let entity = app.world_mut().spawn(Mode::Idle).id();
        let after_spawn = Transitions {
            add: 1,
            insert: 1,
            discard: 0,
            remove: 0,
        };
        assert_eq!(transitions(&app), after_spawn);

        app.world_mut().entity_mut(entity).insert(Mode::Idle);
        assert_eq!(
            transitions(&app),
            after_spawn,
            "same variant re-inserted through the hook must not churn the marker",
        );

        *app.world_mut()
            .get_mut::<Mode>(entity)
            .expect("mode should exist") = Mode::Idle;
        app.update();
        assert_eq!(
            transitions(&app),
            after_spawn,
            "same variant re-synced by the Changed system must not churn the marker",
        );
        assert!(app.world().entity(entity).contains::<ModeIdle>());
    }

    #[test]
    fn variant_change_fires_remove_then_add() {
        let mut app = App::new();
        app.add_plugins(ModeEnumFilterPlugin);
        observe_transitions::<ModeRun>(&mut app);

        let entity = app.world_mut().spawn(Mode::Idle).id();
        assert_eq!(transitions(&app), Transitions::default());

        app.world_mut().entity_mut(entity).insert(Mode::Run);
        assert_eq!(
            transitions(&app),
            Transitions {
                add: 1,
                insert: 1,
                discard: 0,
                remove: 0,
            }
        );

        app.world_mut().entity_mut(entity).insert(Mode::Idle);
        assert_eq!(
            transitions(&app),
            Transitions {
                add: 1,
                insert: 1,
                discard: 1,
                remove: 1,
            }
        );
    }

    #[test]
    fn systems_ordered_after_the_set_see_markers_from_in_place_mutation() {
        #[derive(Resource, Default)]
        struct SeenRun(usize);

        let mut app = App::new();
        app.add_plugins(ModeEnumFilterPlugin)
            .init_resource::<SeenRun>()
            .add_systems(
                PreUpdate,
                (|q: Query<(), With<ModeRun>>, mut seen: ResMut<SeenRun>| seen.0 = q.count())
                    .after(EnumFilterSystems),
            );

        let entity = app.world_mut().spawn(Mode::Idle).id();
        app.update();
        assert_eq!(app.world().resource::<SeenRun>().0, 0);

        *app.world_mut()
            .get_mut::<Mode>(entity)
            .expect("mode should exist") = Mode::Run;
        app.update();
        assert_eq!(
            app.world().resource::<SeenRun>().0,
            1,
            "a system after EnumFilterSystems must see the marker in the same frame",
        );
    }

    #[allow(dead_code)]
    #[derive(Component, EnumFilter, Debug, PartialEq, Eq)]
    enum Wide {
        V00,
        V01,
        V02,
        V03,
        V04,
        V05,
        V06,
        V07,
        V08,
        V09,
        V10,
        V11,
        V12,
        V13,
        V14,
        V15,
        V16,
    }

    #[test]
    fn enums_wider_than_bundle_tuple_limit_still_sync() {
        let mut app = App::new();
        app.add_plugins(WideEnumFilterPlugin);

        let entity = app.world_mut().spawn(Wide::V16).id();
        assert!(app.world().entity(entity).contains::<WideV16>());

        app.world_mut().entity_mut(entity).insert(Wide::V00);
        let entity_ref = app.world().entity(entity);
        assert!(entity_ref.contains::<WideV00>());
        assert!(!entity_ref.contains::<WideV16>());

        app.world_mut().entity_mut(entity).remove::<Wide>();
        assert!(!app.world().entity(entity).contains::<WideV00>());
    }

    #[test]
    fn changed_system_still_catches_mutable_enum_updates() {
        let mut app = App::new();
        app.add_plugins(ModeEnumFilterPlugin);

        let entity = app.world_mut().spawn(Mode::Idle).id();
        *app.world_mut()
            .get_mut::<Mode>(entity)
            .expect("mode should exist") = Mode::Run;

        app.update();

        let entity_ref = app.world().entity(entity);
        assert!(!entity_ref.contains::<ModeIdle>());
        assert!(entity_ref.contains::<ModeRun>());
    }

    #[derive(Debug, PartialEq, Eq)]
    struct TaskResult;

    #[derive(Debug, PartialEq, Eq)]
    struct TaskError;

    #[allow(dead_code)]
    #[derive(Component, EnumFilter, Default, Debug, PartialEq, Eq)]
    enum TaskStatus {
        #[default]
        Created,
        Queued,
        Executing,
        Done(TaskResult),
        Failed(TaskError),
        Canceled,
    }

    #[test]
    fn tuple_variant_markers_are_synced_by_variant() {
        let mut app = App::new();
        app.add_plugins(TaskStatusEnumFilterPlugin);

        let entity = app.world_mut().spawn(TaskStatus::Done(TaskResult)).id();
        let entity_ref = app.world().entity(entity);

        assert!(!entity_ref.contains::<TaskStatusCreated>());
        assert!(entity_ref.contains::<TaskStatusDone>());
        assert!(!entity_ref.contains::<TaskStatusFailed>());
    }

    #[test]
    fn tuple_variant_markers_update_when_payload_variant_changes() {
        let mut app = App::new();
        app.add_plugins(TaskStatusEnumFilterPlugin);

        let entity = app.world_mut().spawn(TaskStatus::Done(TaskResult)).id();
        app.world_mut()
            .entity_mut(entity)
            .insert(TaskStatus::Failed(TaskError));

        let entity_ref = app.world().entity(entity);
        assert!(!entity_ref.contains::<TaskStatusDone>());
        assert!(entity_ref.contains::<TaskStatusFailed>());
    }

    #[allow(dead_code)]
    #[derive(Component, EnumFilter, Display, Debug, PartialEq, Eq)]
    enum Lifecycle {
        #[strum(serialize = "Action Required")]
        ActionRequired,
        Tasked,
    }

    #[test]
    fn marker_display_delegates_to_enum_display() {
        assert_eq!(LifecycleActionRequired.to_string(), "Action Required");
        assert_eq!(LifecycleTasked.to_string(), "Tasked");
    }

    #[allow(dead_code)]
    #[derive(Component, EnumFilter, Display, Debug, PartialEq, Eq)]
    enum BasicDisplay {
        Created,
        Canceled,
    }

    #[test]
    fn marker_display_uses_variant_name_without_strum_attrs() {
        assert_eq!(BasicDisplayCreated.to_string(), "Created");
        assert_eq!(BasicDisplayCanceled.to_string(), "Canceled");
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    struct FruitEntry {
        kind: Fruit,
    }

    #[derive(Component, EnumFilterCollection, Debug, Clone, PartialEq, Eq, Default)]
    #[enum_filter_collection(enum = Fruit, iter = "fruits", map = "kind")]
    struct FruitBasket {
        fruits: Vec<FruitEntry>,
    }

    #[derive(Component, EnumFilterCollection, Debug, Clone, PartialEq, Eq, Default)]
    #[enum_filter_collection(enum = Fruit, iter = "fruits")]
    struct DirectFruitBasket {
        fruits: Vec<Fruit>,
    }

    #[derive(Component, EnumFilter, Debug, Clone, Copy, PartialEq, Eq)]
    enum Fruit {
        Apple,
        Banana,
        Orange,
    }

    #[test]
    fn collection_markers_are_synced_immediately_on_insert() {
        let mut app = App::new();
        app.add_plugins(FruitBasketEnumFilterPlugin);

        let entity = app
            .world_mut()
            .spawn(FruitBasket {
                fruits: vec![
                    FruitEntry { kind: Fruit::Apple },
                    FruitEntry {
                        kind: Fruit::Banana,
                    },
                ],
            })
            .id();

        let entity_ref = app.world().entity(entity);
        assert!(entity_ref.contains::<FruitApple>());
        assert!(entity_ref.contains::<FruitBanana>());
        assert!(!entity_ref.contains::<FruitOrange>());
    }

    #[test]
    fn collection_reinsert_keeps_retained_markers_untouched() {
        let mut app = App::new();
        app.add_plugins(FruitBasketEnumFilterPlugin);
        observe_transitions::<FruitApple>(&mut app);

        let entity = app
            .world_mut()
            .spawn(FruitBasket {
                fruits: vec![FruitEntry { kind: Fruit::Apple }],
            })
            .id();
        let after_spawn = Transitions {
            add: 1,
            insert: 1,
            discard: 0,
            remove: 0,
        };
        assert_eq!(transitions(&app), after_spawn);

        app.world_mut().entity_mut(entity).insert(FruitBasket {
            fruits: vec![
                FruitEntry { kind: Fruit::Apple },
                FruitEntry {
                    kind: Fruit::Banana,
                },
            ],
        });
        assert_eq!(
            transitions(&app),
            after_spawn,
            "a marker kept across a collection update must not churn",
        );
        let entity_ref = app.world().entity(entity);
        assert!(entity_ref.contains::<FruitApple>());
        assert!(entity_ref.contains::<FruitBanana>());
    }

    #[test]
    fn collection_markers_are_synced_on_change() {
        let mut app = App::new();
        app.add_plugins(FruitBasketEnumFilterPlugin);

        let entity = app
            .world_mut()
            .spawn(FruitBasket {
                fruits: vec![FruitEntry { kind: Fruit::Apple }],
            })
            .id();

        app.world_mut().entity_mut(entity).insert(FruitBasket {
            fruits: vec![FruitEntry {
                kind: Fruit::Orange,
            }],
        });

        let entity_ref = app.world().entity(entity);
        assert!(!entity_ref.contains::<FruitApple>());
        assert!(!entity_ref.contains::<FruitBanana>());
        assert!(entity_ref.contains::<FruitOrange>());
    }

    #[test]
    fn collection_markers_are_removed_on_component_removal() {
        let mut app = App::new();
        app.add_plugins(FruitBasketEnumFilterPlugin);

        let entity = app
            .world_mut()
            .spawn(FruitBasket {
                fruits: vec![FruitEntry { kind: Fruit::Apple }],
            })
            .id();

        app.world_mut().entity_mut(entity).remove::<FruitBasket>();

        let entity_ref = app.world().entity(entity);
        assert!(!entity_ref.contains::<FruitApple>());
        assert!(!entity_ref.contains::<FruitBanana>());
        assert!(!entity_ref.contains::<FruitOrange>());
    }

    #[test]
    fn direct_collection_markers_are_synced_immediately_on_insert() {
        let mut app = App::new();
        app.add_plugins(DirectFruitBasketEnumFilterPlugin);

        let entity = app
            .world_mut()
            .spawn(DirectFruitBasket {
                fruits: vec![Fruit::Apple, Fruit::Banana],
            })
            .id();

        let entity_ref = app.world().entity(entity);
        assert!(entity_ref.contains::<FruitApple>());
        assert!(entity_ref.contains::<FruitBanana>());
        assert!(!entity_ref.contains::<FruitOrange>());
    }

    #[derive(Component, Debug, Clone, PartialEq, Eq)]
    struct DownloadProgress {
        percent: u8,
    }

    #[allow(dead_code)]
    #[derive(Component, EnumFilter, Debug, Clone, PartialEq, Eq)]
    enum Download {
        Queued,
        #[enum_filter(extract)]
        Active(DownloadProgress),
        Finished,
    }

    #[test]
    fn extracted_payload_is_synced_immediately_on_insert() {
        let mut app = App::new();
        app.add_plugins(DownloadEnumFilterPlugin);

        let entity = app
            .world_mut()
            .spawn(Download::Active(DownloadProgress { percent: 40 }))
            .id();

        let entity_ref = app.world().entity(entity);
        assert!(entity_ref.contains::<DownloadActive>());
        assert_eq!(
            entity_ref.get::<DownloadProgress>(),
            Some(&DownloadProgress { percent: 40 })
        );
    }

    #[test]
    fn extracted_payload_update_replaces_without_readding() {
        let mut app = App::new();
        app.add_plugins(DownloadEnumFilterPlugin);
        observe_transitions::<DownloadProgress>(&mut app);

        let entity = app
            .world_mut()
            .spawn(Download::Active(DownloadProgress { percent: 40 }))
            .id();
        assert_eq!(
            transitions(&app),
            Transitions {
                add: 1,
                insert: 1,
                discard: 0,
                remove: 0,
            }
        );

        app.world_mut()
            .entity_mut(entity)
            .insert(Download::Active(DownloadProgress { percent: 80 }));
        assert_eq!(
            transitions(&app),
            Transitions {
                add: 1,
                insert: 2,
                discard: 1,
                remove: 0,
            },
            "a payload update within the same variant is a replace, not a remove and add",
        );
        assert_eq!(
            app.world().entity(entity).get::<DownloadProgress>(),
            Some(&DownloadProgress { percent: 80 })
        );
    }

    #[test]
    fn despawning_from_a_marker_observer_does_not_panic() {
        let mut app = App::new();
        app.add_plugins(DownloadEnumFilterPlugin);
        // The marker lands before the extracted payload does. An observer
        // reacting to the marker by despawning the entity must not make the
        // trailing payload insert blow up on the corpse.
        app.add_observer(|add: On<Add, DownloadActive>, mut commands: Commands| {
            commands.entity(add.entity).despawn();
        });

        let entity = app.world_mut().spawn(Download::Queued).id();
        app.world_mut()
            .entity_mut(entity)
            .insert(Download::Active(DownloadProgress { percent: 40 }));

        assert!(app.world().get_entity(entity).is_err());
    }

    #[test]
    fn extracted_payload_is_removed_when_variant_changes() {
        let mut app = App::new();
        app.add_plugins(DownloadEnumFilterPlugin);

        let entity = app
            .world_mut()
            .spawn(Download::Active(DownloadProgress { percent: 40 }))
            .id();
        app.world_mut()
            .entity_mut(entity)
            .insert(Download::Finished);

        let entity_ref = app.world().entity(entity);
        assert!(entity_ref.contains::<DownloadFinished>());
        assert!(!entity_ref.contains::<DownloadProgress>());
    }

    #[test]
    fn extracted_payload_is_removed_on_component_removal() {
        let mut app = App::new();
        app.add_plugins(DownloadEnumFilterPlugin);

        let entity = app
            .world_mut()
            .spawn(Download::Active(DownloadProgress { percent: 40 }))
            .id();
        app.world_mut().entity_mut(entity).remove::<Download>();

        let entity_ref = app.world().entity(entity);
        assert!(!entity_ref.contains::<DownloadProgress>());
    }

    #[test]
    fn extracted_payload_is_synced_on_in_place_mutation() {
        let mut app = App::new();
        app.add_plugins(DownloadEnumFilterPlugin);

        let entity = app
            .world_mut()
            .spawn(Download::Active(DownloadProgress { percent: 40 }))
            .id();
        *app.world_mut()
            .get_mut::<Download>(entity)
            .expect("download should exist") = Download::Active(DownloadProgress { percent: 80 });

        app.update();

        let entity_ref = app.world().entity(entity);
        assert_eq!(
            entity_ref.get::<DownloadProgress>(),
            Some(&DownloadProgress { percent: 80 })
        );
    }

    #[derive(Component, Debug, Clone, PartialEq, Eq)]
    struct NavigatePayload {
        distance: u32,
    }

    #[allow(dead_code)]
    #[derive(Component, EnumFilter, Debug, Clone, PartialEq, Eq)]
    enum Progress {
        Idle,
        #[enum_filter(extract)]
        Navigate(NavigatePayload),
    }

    #[allow(dead_code)]
    #[derive(Component, EnumFilter, Debug, Clone, PartialEq, Eq)]
    enum Status {
        Created,
        #[enum_filter(extract)]
        Executing(Progress),
    }

    #[test]
    fn extraction_cascades_through_nested_enum_filters() {
        let mut app = App::new();
        app.add_plugins(StatusEnumFilterPlugin)
            .add_plugins(ProgressEnumFilterPlugin);

        let entity = app
            .world_mut()
            .spawn(Status::Executing(Progress::Navigate(NavigatePayload {
                distance: 12,
            })))
            .id();

        app.update();

        let entity_ref = app.world().entity(entity);
        assert!(entity_ref.contains::<StatusExecuting>());
        assert!(entity_ref.contains::<ProgressNavigate>());
        assert_eq!(
            entity_ref.get::<Progress>(),
            Some(&Progress::Navigate(NavigatePayload { distance: 12 }))
        );
        assert_eq!(
            entity_ref.get::<NavigatePayload>(),
            Some(&NavigatePayload { distance: 12 })
        );
    }

    #[test]
    fn extraction_cascade_unwinds_when_outer_variant_changes() {
        let mut app = App::new();
        app.add_plugins(StatusEnumFilterPlugin)
            .add_plugins(ProgressEnumFilterPlugin);

        let entity = app
            .world_mut()
            .spawn(Status::Executing(Progress::Navigate(NavigatePayload {
                distance: 12,
            })))
            .id();
        app.update();

        app.world_mut().entity_mut(entity).insert(Status::Created);
        app.update();

        let entity_ref = app.world().entity(entity);
        assert!(entity_ref.contains::<StatusCreated>());
        assert!(!entity_ref.contains::<Progress>());
        assert!(!entity_ref.contains::<ProgressNavigate>());
        assert!(!entity_ref.contains::<NavigatePayload>());
    }
}
