extern crate self as bevy_filter_enum;

pub use bevy_filter_enum_derive::{EnumFilter, EnumFilterCollection};

/// Shared behavior generated by [`EnumFilter`] for enum values that can sync
/// marker components onto an entity.
pub trait EnumFilterValue {
    /// Returns the generated marker index for this enum value.
    fn marker_index(&self) -> usize;

    /// Inserts the marker component corresponding to a generated marker index.
    fn insert_marker_by_index(index: usize, entity: &mut bevy_ecs::system::EntityCommands<'_>);

    /// Inserts the marker component corresponding to this enum value.
    fn insert_marker(&self, entity: &mut bevy_ecs::system::EntityCommands<'_>) {
        Self::insert_marker_by_index(self.marker_index(), entity);
    }

    /// Removes all marker components generated for this enum type.
    fn remove_markers(entity: &mut bevy_ecs::system::EntityCommands<'_>);
}

/// Re-exports so the derive output can refer to known crate paths.
pub mod __private {
    pub use bevy_app;
    pub use bevy_ecs;
}

#[cfg(test)]
mod tests {
    use bevy_app::App;
    use bevy_ecs::prelude::Component;
    use strum_macros::Display;

    use crate::{EnumFilter, EnumFilterCollection};

    #[derive(Component, EnumFilter, Debug, PartialEq, Eq)]
    enum Mode {
        Idle,
        Run,
    }

    #[test]
    fn markers_are_synced_immediately_on_insert() {
        let mut app = App::new();
        app.add_plugins(ModeEnumFilterPlugin);

        let entity = app.world_mut().spawn(Mode::Idle).id();
        let entity_ref = app.world().entity(entity);

        assert!(entity_ref.contains::<ModeIdle>());
        assert!(!entity_ref.contains::<ModeRun>());
    }

    #[test]
    fn markers_are_removed_immediately_on_component_removal() {
        let mut app = App::new();
        app.add_plugins(ModeEnumFilterPlugin);

        let entity = app.world_mut().spawn(Mode::Idle).id();
        app.world_mut().entity_mut(entity).remove::<Mode>();
        let entity_ref = app.world().entity(entity);

        assert!(!entity_ref.contains::<ModeIdle>());
        assert!(!entity_ref.contains::<ModeRun>());
    }

    #[test]
    fn changed_system_still_catches_mutable_enum_updates() {
        let mut app = App::new();
        app.add_plugins(ModeEnumFilterPlugin);

        let entity = app.world_mut().spawn(Mode::Idle).id();
        *app.world_mut()
            .get_mut::<Mode>(entity)
            .expect("mode should exist") = Mode::Run;

        app.update();

        let entity_ref = app.world().entity(entity);
        assert!(!entity_ref.contains::<ModeIdle>());
        assert!(entity_ref.contains::<ModeRun>());
    }

    #[derive(Debug, PartialEq, Eq)]
    struct TaskResult;

    #[derive(Debug, PartialEq, Eq)]
    struct TaskError;

    #[allow(dead_code)]
    #[derive(Component, EnumFilter, Default, Debug, PartialEq, Eq)]
    enum TaskStatus {
        #[default]
        Created,
        Queued,
        Executing,
        Done(TaskResult),
        Failed(TaskError),
        Canceled,
    }

    #[test]
    fn tuple_variant_markers_are_synced_by_variant() {
        let mut app = App::new();
        app.add_plugins(TaskStatusEnumFilterPlugin);

        let entity = app.world_mut().spawn(TaskStatus::Done(TaskResult)).id();
        let entity_ref = app.world().entity(entity);

        assert!(!entity_ref.contains::<TaskStatusCreated>());
        assert!(entity_ref.contains::<TaskStatusDone>());
        assert!(!entity_ref.contains::<TaskStatusFailed>());
    }

    #[test]
    fn tuple_variant_markers_update_when_payload_variant_changes() {
        let mut app = App::new();
        app.add_plugins(TaskStatusEnumFilterPlugin);

        let entity = app.world_mut().spawn(TaskStatus::Done(TaskResult)).id();
        app.world_mut()
            .entity_mut(entity)
            .insert(TaskStatus::Failed(TaskError));

        let entity_ref = app.world().entity(entity);
        assert!(!entity_ref.contains::<TaskStatusDone>());
        assert!(entity_ref.contains::<TaskStatusFailed>());
    }

    #[allow(dead_code)]
    #[derive(Component, EnumFilter, Display, Debug, PartialEq, Eq)]
    enum Lifecycle {
        #[strum(serialize = "Action Required")]
        ActionRequired,
        Tasked,
    }

    #[test]
    fn marker_display_delegates_to_enum_display() {
        assert_eq!(LifecycleActionRequired.to_string(), "Action Required");
        assert_eq!(LifecycleTasked.to_string(), "Tasked");
    }

    #[allow(dead_code)]
    #[derive(Component, EnumFilter, Display, Debug, PartialEq, Eq)]
    enum BasicDisplay {
        Created,
        Canceled,
    }

    #[test]
    fn marker_display_uses_variant_name_without_strum_attrs() {
        assert_eq!(BasicDisplayCreated.to_string(), "Created");
        assert_eq!(BasicDisplayCanceled.to_string(), "Canceled");
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    struct FruitEntry {
        kind: Fruit,
    }

    #[derive(Component, EnumFilterCollection, Debug, Clone, PartialEq, Eq, Default)]
    #[enum_filter_collection(enum = Fruit, iter = "fruits", map = "kind")]
    struct FruitBasket {
        fruits: Vec<FruitEntry>,
    }

    #[derive(Component, EnumFilterCollection, Debug, Clone, PartialEq, Eq, Default)]
    #[enum_filter_collection(enum = Fruit, iter = "fruits")]
    struct DirectFruitBasket {
        fruits: Vec<Fruit>,
    }

    #[derive(Component, EnumFilter, Debug, Clone, Copy, PartialEq, Eq)]
    enum Fruit {
        Apple,
        Banana,
        Orange,
    }

    #[test]
    fn collection_markers_are_synced_immediately_on_insert() {
        let mut app = App::new();
        app.add_plugins(FruitBasketEnumFilterPlugin);

        let entity = app
            .world_mut()
            .spawn(FruitBasket {
                fruits: vec![
                    FruitEntry { kind: Fruit::Apple },
                    FruitEntry {
                        kind: Fruit::Banana,
                    },
                ],
            })
            .id();

        let entity_ref = app.world().entity(entity);
        assert!(entity_ref.contains::<FruitApple>());
        assert!(entity_ref.contains::<FruitBanana>());
        assert!(!entity_ref.contains::<FruitOrange>());
    }

    #[test]
    fn collection_markers_are_synced_on_change() {
        let mut app = App::new();
        app.add_plugins(FruitBasketEnumFilterPlugin);

        let entity = app
            .world_mut()
            .spawn(FruitBasket {
                fruits: vec![FruitEntry { kind: Fruit::Apple }],
            })
            .id();

        app.world_mut().entity_mut(entity).insert(FruitBasket {
            fruits: vec![FruitEntry {
                kind: Fruit::Orange,
            }],
        });

        let entity_ref = app.world().entity(entity);
        assert!(!entity_ref.contains::<FruitApple>());
        assert!(!entity_ref.contains::<FruitBanana>());
        assert!(entity_ref.contains::<FruitOrange>());
    }

    #[test]
    fn collection_markers_are_removed_on_component_removal() {
        let mut app = App::new();
        app.add_plugins(FruitBasketEnumFilterPlugin);

        let entity = app
            .world_mut()
            .spawn(FruitBasket {
                fruits: vec![FruitEntry { kind: Fruit::Apple }],
            })
            .id();

        app.world_mut().entity_mut(entity).remove::<FruitBasket>();

        let entity_ref = app.world().entity(entity);
        assert!(!entity_ref.contains::<FruitApple>());
        assert!(!entity_ref.contains::<FruitBanana>());
        assert!(!entity_ref.contains::<FruitOrange>());
    }

    #[test]
    fn direct_collection_markers_are_synced_immediately_on_insert() {
        let mut app = App::new();
        app.add_plugins(DirectFruitBasketEnumFilterPlugin);

        let entity = app
            .world_mut()
            .spawn(DirectFruitBasket {
                fruits: vec![Fruit::Apple, Fruit::Banana],
            })
            .id();

        let entity_ref = app.world().entity(entity);
        assert!(entity_ref.contains::<FruitApple>());
        assert!(entity_ref.contains::<FruitBanana>());
        assert!(!entity_ref.contains::<FruitOrange>());
    }

    #[derive(Component, Debug, Clone, PartialEq, Eq)]
    struct DownloadProgress {
        percent: u8,
    }

    #[allow(dead_code)]
    #[derive(Component, EnumFilter, Debug, Clone, PartialEq, Eq)]
    enum Download {
        Queued,
        #[enum_filter(extract)]
        Active(DownloadProgress),
        Finished,
    }

    #[test]
    fn extracted_payload_is_synced_immediately_on_insert() {
        let mut app = App::new();
        app.add_plugins(DownloadEnumFilterPlugin);

        let entity = app
            .world_mut()
            .spawn(Download::Active(DownloadProgress { percent: 40 }))
            .id();

        let entity_ref = app.world().entity(entity);
        assert!(entity_ref.contains::<DownloadActive>());
        assert_eq!(
            entity_ref.get::<DownloadProgress>(),
            Some(&DownloadProgress { percent: 40 })
        );
    }

    #[test]
    fn extracted_payload_is_removed_when_variant_changes() {
        let mut app = App::new();
        app.add_plugins(DownloadEnumFilterPlugin);

        let entity = app
            .world_mut()
            .spawn(Download::Active(DownloadProgress { percent: 40 }))
            .id();
        app.world_mut()
            .entity_mut(entity)
            .insert(Download::Finished);

        let entity_ref = app.world().entity(entity);
        assert!(entity_ref.contains::<DownloadFinished>());
        assert!(!entity_ref.contains::<DownloadProgress>());
    }

    #[test]
    fn extracted_payload_is_removed_on_component_removal() {
        let mut app = App::new();
        app.add_plugins(DownloadEnumFilterPlugin);

        let entity = app
            .world_mut()
            .spawn(Download::Active(DownloadProgress { percent: 40 }))
            .id();
        app.world_mut().entity_mut(entity).remove::<Download>();

        let entity_ref = app.world().entity(entity);
        assert!(!entity_ref.contains::<DownloadProgress>());
    }

    #[test]
    fn extracted_payload_is_synced_on_in_place_mutation() {
        let mut app = App::new();
        app.add_plugins(DownloadEnumFilterPlugin);

        let entity = app
            .world_mut()
            .spawn(Download::Active(DownloadProgress { percent: 40 }))
            .id();
        *app.world_mut()
            .get_mut::<Download>(entity)
            .expect("download should exist") = Download::Active(DownloadProgress { percent: 80 });

        app.update();

        let entity_ref = app.world().entity(entity);
        assert_eq!(
            entity_ref.get::<DownloadProgress>(),
            Some(&DownloadProgress { percent: 80 })
        );
    }

    #[derive(Component, Debug, Clone, PartialEq, Eq)]
    struct NavigatePayload {
        distance: u32,
    }

    #[allow(dead_code)]
    #[derive(Component, EnumFilter, Debug, Clone, PartialEq, Eq)]
    enum Progress {
        Idle,
        #[enum_filter(extract)]
        Navigate(NavigatePayload),
    }

    #[allow(dead_code)]
    #[derive(Component, EnumFilter, Debug, Clone, PartialEq, Eq)]
    enum Status {
        Created,
        #[enum_filter(extract)]
        Executing(Progress),
    }

    #[test]
    fn extraction_cascades_through_nested_enum_filters() {
        let mut app = App::new();
        app.add_plugins(StatusEnumFilterPlugin)
            .add_plugins(ProgressEnumFilterPlugin);

        let entity = app
            .world_mut()
            .spawn(Status::Executing(Progress::Navigate(NavigatePayload {
                distance: 12,
            })))
            .id();

        app.update();

        let entity_ref = app.world().entity(entity);
        assert!(entity_ref.contains::<StatusExecuting>());
        assert!(entity_ref.contains::<ProgressNavigate>());
        assert_eq!(
            entity_ref.get::<Progress>(),
            Some(&Progress::Navigate(NavigatePayload { distance: 12 }))
        );
        assert_eq!(
            entity_ref.get::<NavigatePayload>(),
            Some(&NavigatePayload { distance: 12 })
        );
    }

    #[test]
    fn extraction_cascade_unwinds_when_outer_variant_changes() {
        let mut app = App::new();
        app.add_plugins(StatusEnumFilterPlugin)
            .add_plugins(ProgressEnumFilterPlugin);

        let entity = app
            .world_mut()
            .spawn(Status::Executing(Progress::Navigate(NavigatePayload {
                distance: 12,
            })))
            .id();
        app.update();

        app.world_mut().entity_mut(entity).insert(Status::Created);
        app.update();

        let entity_ref = app.world().entity(entity);
        assert!(entity_ref.contains::<StatusCreated>());
        assert!(!entity_ref.contains::<Progress>());
        assert!(!entity_ref.contains::<ProgressNavigate>());
        assert!(!entity_ref.contains::<NavigatePayload>());
    }
}
